### ISSUE TITLE
Disable no-var and prefer-arrow-callback in es5.js config?

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/eslint-config-nodesecurity#1]
Ref: https://github.com/nodesecurity/nsp/pull/45#issuecomment-153284435

I think we may want to override/disable these 2 rules in the es5.js file:

``` js
'prefer-arrow-callback': 0,
'no-var': 0
```

It looks like those are coming from the [**eslint-config-hapi**](https://github.com/continuationlabs/eslint-config-hapi/blob/6ff77025231d82a71596c70a310b85b82ea10693/lib/index.js#L69-L70) module.

**Comment by latentflip** [comment]
Ah yeah looks like that config got es6ified so we will need to workaround it somehow. Maybe we should just have a separate es5 config and copy what we need from the hapi one, rather than trying to undo each of the es6 changes hapi config adds moving forward?

**Comment by nlf** [comment]
yeah, i'll refactor this to remove our dependency on the hapi config

**Comment by pdehaan** [comment]
Filed an upstream request (https://github.com/continuationlabs/eslint-config-hapi/issues/24) to add support for an ES5 compatible config of **eslint-config-hapi**.

**Comment by nlf** [comment]
i doubt they'll be interested in maintaining something they don't use, but worth a shot :)

**Comment by cjihrig** [comment]
@nlf I exposed an ES5 config from the hapi config. It looks like you've already refactored your project, so this is more just an FYI.

**Comment by nlf** [comment]
nice! thanks for letting me know

**Comment by pdehaan** [comment]
Awesome, thanks again @cjihrig!

I actually played with this the other day, and we could go back to extending the official **eslint-config-hapi** config (and making it a dependency of **eslint-config-gulp**), then we can just export our **eslint-config-gulp** config as either of the following:

``` js
var cfg = require('eslint-config-hapi/lib/es5');

cfg.rules['hapi/hapi-scope-start'] = 0;
cfg.rules['comma-dangle'] = [2, 'always-multiline'];
cfg.rules['func-style'] = 0;
cfg.rules['indent'] = [2, 2];
cfg.rules['space-before-function-paren'] = [2, 'never'];

module.exports = cfg;
```

&mdash; or &mdash;

``` js
module.exports = {
  "extends": require.resolve('eslint-config-hapi/lib/es5'),
  "rules": {
    "hapi/hapi-scope-start": 0,

    "comma-dangle": [2, "always-multiline"],
    "func-style": 0,
    "indent": [2, 2],
    "space-before-function-paren": [2, "never"]
  }
};
```

We _shouldn't_ need **eslint-config-hapi** as a dependency in any of our projects, but we'd still need to bundle **eslint-plugin-hapi** since I can't figure out how to package that into our custom ESLint config.
